### Get All Users

GET http://localhost:3000/users
Content-Type: application/json

###

### Register User

POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "PedroAlison",
    "email": "pedro@gmail.com",
    "password": "Pedroca"
}

###

### Login User

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "pedro@gmail.com",
    "password": "Pedroca"
}