
### Requição dos dados da tabela user 
curl -X GET http://localhost:3000/users

###

### Requisição de Registro
curl -X POST http://localhost:3000/register -H "Content-Type: application/json" -d '{

    "name": "nathan", 
    "email": "nathan@exemplo.com", 
    "password": "senhaForte"
    
    }'

###

### Requisição de login
curl -X POST http://localhost:3000/login -H "Content-Type: application/json" -d '{

    "email": "nathan@exemplo.com", 
    "password": "senhaForte"
    
    }'


