### Tabela de Dados dos Livros
curl -X GET http://localhost:3000/books

### Registro de Livro
curl -X POST http://localhost:3000/books -H "Content-Type: application/json" -d '{"title": "Jogador N1", "author": "Ernest Cline", "price": "79.90"}'